[package]
name = "fstree"
version = "0.1.1"
edition = "2024"
authors = ["Abdullah Abdulkhaleq"]
license = "MIT"
repository = "https://github.com/AbdullahNamespace/fstree"
homepage = "https://github.com/AbdullahNamespace/fstree"
documentation = "https://docs.rs/fstree"
readme = "README.md"
description = "fstree - A blazing fast File System Tree command in Rust with smart file type icons."
keywords = ["cli", "tree", "terminal", "visualization", "file-system-tree"]
categories = ["command-line-utilities", "filesystem", "development-tools"]

[[bin]]
name = "fstree"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
anyhow = "1.0"
once_cell = "1.18"
